import crypto from 'crypto'
import type { InitConfig } from '../lib/types'

export function generateEnvFile(config: InitConfig): string {
  const lines = [
    '# Second Brain Configuration',
    '# Generated by second-brain init',
    '',
    '# Database',
    `DATABASE_URL=${config.database.connectionString}`,
    '',
    '# Vault',
    `VAULT_PATH=${config.vault.path}`,
    '',
    '# Auth',
    `BETTER_AUTH_SECRET=${config.auth.authSecret || crypto.randomBytes(32).toString('base64')}`,
    `BETTER_AUTH_URL=${config.appUrl}`,
    '',
    '# Admin (used on first startup to seed database)',
    `ADMIN_EMAIL=${config.auth.adminEmail}`,
    `ADMIN_PASSWORD=${config.auth.adminPassword}`,
    `ADMIN_NAME=${config.auth.adminName}`
  ]

  if (config.integrations.gotifyUrl) {
    lines.push(
      '',
      '# Notifications',
      `GOTIFY_URL=${config.integrations.gotifyUrl}`,
      `GOTIFY_TOKEN=${config.integrations.gotifyToken || ''}`
    )
  }

  lines.push('')
  return lines.join('\n')
}
