import crypto from 'crypto'
import type { InitConfig } from '../lib/types'

export function generateEnvFile(config: InitConfig): string {
  const lines = [
    '# Cognova Configuration',
    '# Generated by cognova init',
    '',
    '# Database',
    `DATABASE_URL=${config.database.connectionString}`,
    '',
    '# Vault',
    `VAULT_PATH=${config.vault.path}`,
    '',
    '# Network',
    `ACCESS_MODE=${config.accessMode}`,
    ...(config.accessMode !== 'localhost' ? ['HOST=0.0.0.0'] : []),
    '',
    '# Auth',
    `BETTER_AUTH_SECRET=${config.auth.authSecret || crypto.randomBytes(32).toString('base64')}`,
    `BETTER_AUTH_URL=${config.accessMode === 'any' ? '' : config.appUrl}`,
    '',
    '# Admin (used on first startup to seed database)',
    `ADMIN_EMAIL=${config.auth.adminEmail}`,
    `ADMIN_PASSWORD=${config.auth.adminPassword}`,
    `ADMIN_NAME=${config.auth.adminName}`,
    '',
    '# Agent personality (used by the web UI)',
    `AGENT_NAME=${config.personality.agentName}`,
    `AGENT_TONE=${config.personality.tone}`
  ]

  lines.push('')
  return lines.join('\n')
}
